### ISSUE TITLE
Remove frontmatter from result

### ISSUE THREAD

**Issue by Lisandra-dev** [mgmeyers/obsidian-easy-bake#3]
If the embedded file contains frontmatter, the baked file will contains also the frontmatter, breaking the markdown/contents.

Note: It happens only for entire cited file.

**Comment by mgmeyers** [comment]
Fixed!

**Comment by Lisandra-dev** [comment]
Hello!
It doesn't seems to work properly:
Expected: 
![image](https://github.com/mgmeyers/obsidian-easy-bake/assets/30244939/512a2add-8e3f-4123-9b9c-3a89ab5e398e)

Result:
![image](https://github.com/mgmeyers/obsidian-easy-bake/assets/30244939/0bbb0fba-e5cc-4c4b-9aa1-4a95987489b7)

**Comment by mgmeyers** [comment]
Hmm, try the latest version and see if that fixes things for you @Lisandra-dev

**Comment by Lisandra-dev** [comment]
Yes, it's perfect! Thank you :)
